# Generated by Django 2.2.4 on 2019-12-23 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('askpupkin', '0003_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data_create',
            field=models.DateField(default=datetime.datetime(2019, 12, 23, 9, 31, 10, 947620, tzinfo=utc)),
        ),
    ]
