# Generated by Django 2.2.4 on 2019-12-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askpupkin', '0004_auto_20191223_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
